=== AhmedDaali/AE_2_XML_DTD_XSD/ejercicio_biblioteca_xsd/biblioteca.xsd
<?xml version="1.0"?>
<!--ME FALTA REVISAR:
        - QUE LOS ID NO SE PUEDAN REPETIR-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:annotation>
    <xs:documentation>
        Este es un esquema que nos permite la validación del archivo "biblioteca.xml".
    </xs:documentation>
</xs:annotation>

    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libro" maxOccurs="unbounded">
                                <xs:complexType>

                                    <xs:sequence>
                                        
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="indice" type="xs:string"/>
                                        <xs:element name="capitulos">

                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="capitulo" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="titulo" type="xs:string"/>
                                                                <xs:element name="contenido">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="enlace" type="xs:string"/>
                                                                    </xs:complexType>
                                                            </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="paginas" type="xs:integer" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="sinopsis" type="xs:string"/>
                                    </xs:sequence>
                    
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="L\d\d\d\d"/> <!--Con esto restringimos que el formato del id del libro sea como pide el ejercicio -->
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="paginas" type="xs:integer" use="required"/>
                                    <xs:attribute name="tipo_clase" use="required">
                                        <xs:simpleType>                             
                                            <xs:restriction base="xs:string">   <!-- Con esto restringimos los valores de el campo "tipo_clase" a los que indica el ejercicio"-->
                                                <xs:enumeration value="novela"/>
                                                <xs:enumeration value="infantil"/>
                                                <xs:enumeration value="didáctico"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                
                <xs:element name="revistas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="revista" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="numero" type="xs:integer"/>
                                        <xs:element name="indice" type="xs:string"/>
                                        <xs:element name="secciones_revista">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="seccion_revista" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="contenido">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="enlace" type="xs:string"/>
                                                                    </xs:complexType>
                                                                </xs:element>  
                                                            </xs:sequence>
                                                            <xs:attribute name="paginas" type="xs:integer" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>

                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="([R][0-9]+)"/> <!--Con esto restringimos que el formato del id del libro sea como pide el ejercicio -->
                                            </xs:restriction>
                                    </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required"> <!-- Con esto restringimos los valores de el campo "tipo_clase" a los que indica el ejercicio"-->
                                        <xs:simpleType>                             
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="corazón"/>
                                                <xs:enumeration value="investigación"/>
                                                <xs:enumeration value="informática"/>
                                                <xs:enumeration value="coches"/>
                                                <xs:enumeration value="otras"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="paginas" type="xs:integer" use="required"/>
                                    

                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="periodicos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="periodico" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="indice" type="xs:string"/>
                                        <xs:element name="secciones_periodico">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="seccion_periodico" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="articulo">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="contenido">
                                                                                <xs:complexType>
                                                                                    <xs:attribute name="enlace" type="xs:string"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="autor" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="tipo_seccion" use="required"> <!-- Con esto restringimos los valores de el campo "tipo_clase" a los que indica el ejercicio"-->
                                                                <xs:simpleType>                             
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="económica"/>
                                                                        <xs:enumeration value="opinión"/>
                                                                        <xs:enumeration value="deportes"/>
                                                                        <xs:enumeration value="nacional"/>
                                                                        <xs:enumeration value="internacional"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>

                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="P\d\d\d\d"/> <!--Con esto restringimos que el formato del id del libro sea como pide el ejercicio -->
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required">
                                        <xs:simpleType>                             
                                            <xs:restriction base="xs:string">   <!-- Con esto restringimos los valores de el campo "tipo_clase" a los que indica el ejercicio"-->
                                                <xs:enumeration value="nacionales"/>
                                                <xs:enumeration value="internacionales"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="fecha_publicacion" type="xs:date" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>

            
        </xs:complexType>
    </xs:element>
  
</xs:schema>

=== AhmedDaali/AE_2_XML_DTD_XSD/ejercicio_biblioteca_xsd/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    <libros>
        <libro id="L0001" paginas="323" tipo_clase="novela">
            
            <titulo>El hobbit</titulo>
            <indice>
                 1. Una tertulia inesperada ........ 9 
                 2. Carnero asado ........ 29 
                 3. Un breve descanso ........ 41 
                 4. Sobre la colina y bajo la colina ........ 48 
                 5. Acertijos en las tinieblas ........ 58 
                 6. De la sartén al fuego ........ 75 
                 7. Extraños aposentos ........ 90 
                 8. Moscas y arañas ........ 110 
                 9. Barriles de contrabando ........ 131 
                10. Una cálida bienvenida ........ 144 
                11. En el umbral ........ 153 
                12. Información secreta ........ 160 
                13. Nadie en casa ........ 176 
                14. Fuego y agua ........ 185 
                15. El encuentro de las nubes ........ 193 
                16. Un ladrón en la noche ........ 201 
                17. Las nubes estallan ........ 206 
                18. El viaje de vuelta ........ 215 
                19. La última jornada ........ 222 
            </indice>
            
            <capitulos>
                <capitulo paginas="20">
                    <titulo>Una tertulia inesperada</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/unaTertuliaInesperada"/>
                </capitulo>
                
                <capitulo paginas="21">
                    <titulo>Carnero asado</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/carneroAsado"/>
                </capitulo>
                
                <capitulo paginas="7">
                    <titulo>Un breve descanso</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/unBreveDescanso"/>
                </capitulo>

                <capitulo paginas="10">
                    <titulo>Sobre la colina y bajo la colina</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/sobreLaColinaYBajoLaColina"/>
                </capitulo>

                <capitulo paginas="30">
                    <titulo>Acertijos en las tinieblas</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/acertijosEnLasTinieblas"/>
                </capitulo>

                <capitulo paginas="20">
                    <titulo>De la sartén al fuego</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/deLaSartenAlFuego"/>
                </capitulo>

                <capitulo paginas="20">
                    <titulo>Extraños aposentos</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/extranosAposentos"/>
                </capitulo>

                <capitulo paginas="32">
                    <titulo>Moscas y arañas</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/moscasYAranas"/>
                </capitulo>

                <capitulo paginas="30">
                    <titulo>Barriles de contrabando</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/barrilesDeContrabando"/>
                </capitulo>

                <capitulo paginas="28">
                    <titulo>Una cálida bienvenida</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/unaCalidaBienvenida"/>
                </capitulo>

                <capitulo paginas="12">
                    <titulo>En el umbral</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/enElUmbral"/>
                </capitulo>

                <capitulo paginas="24">
                    <titulo>Información secreta</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/informacionSecreta"/>
                </capitulo>

                <capitulo paginas="40">
                    <titulo>Nadie en casa</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/nadieEnCasa"/>
                </capitulo>

                <capitulo paginas="11">
                    <titulo>Fuego y agua</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/fuegoYAgua"/>
                </capitulo>

                <capitulo paginas="8">
                    <titulo>El encuentro de las nubes</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/elEncuentroDeLasNubes"/>
                </capitulo>

                <capitulo paginas="22">
                    <titulo>Las nubes estallan</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/lasNubesEstallan"/>
                </capitulo>

                <capitulo paginas="21">
                    <titulo>El viaje de vuelta</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/elViajeDeVuelta"/>
                </capitulo>

                <capitulo paginas="14">
                    <titulo>La última jornada</titulo>
                    <contenido enlace="https://elhobbit.com/estoEsUnEnlaceInventado/laUltimaJornada"/>
                </capitulo>

            </capitulos>
            
            <sinopsis>
                La historia narra el viaje de un hobbit llamado Bilbo Bolsón, al que no le gustan las aventuras, a la Montaña Solitaria en busca del tesoro robado por el dragón Smaug años atrás. 
                
                Todo empieza un inesperado día en el que Bilbo recibe la visita de Gandalf el Gris junto con 13 enanos, entre los que se cuenta a Thorin, Escudo-de-Roble, a cuya familia le fue robado el tesoro. 
                
                Algunos de los hechos narrados en El Hobbit influirán en los acontecimientos posteriores de El Señor de los Anillos. 
            </sinopsis>
        </libro>
    

        <libro id="L0002" paginas="521" tipo_clase="didáctico">
            <titulo>Curso de programacion Java</titulo>
            <indice>
                
                     1. CUESTIONES BÁSICAS SOBRE JAVA
                     2. INSTALAR JAVA EN NUESTRO ORDENADOR Y DAR LOS PRIMEROS PASOS
                     3. CONCEPTOS BÁSICOS DE PROGRAMACIÓN ORIENTADA A OBJETOS. CLASES Y OBJETOS.
                     4. ESCRITURA BÁSICA DE CÓDIGO Y ESTRUCTURAS DE DECISIÓN
                     5. ESTRUCTURAR EL CÓDIGO EN JAVA      
                     6. LIBRERÍAS DEL API DE JAVA. BIBLIOTECAS DE CLASES. 
                     7. CONSTRUIR UN PROGRAMA CON JAVA
                     8. BUCLES, COLECCIONES DE OBJETOS Y RECORRIDOS DE COLECCIONES  
                     9. MÁS CONCEPTOS Y CUESTIONES BÁSICAS DE JAVA
                    10. HERENCIA EN JAVA. ¿QUÉ ES? ¿PARA QUÉ SIRVE?
                    11. IR MÁS ALLÁ EN JAVA: SWING, GESTIÓN DE ERRORES Y MÁS.
                </indice>
            <capitulos>
                <capitulo paginas="12">
                    <titulo>CUESTIONES BÁSICAS SOBRE JAVA</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>
                
                <capitulo paginas="16">
                    <titulo>INSTALAR JAVA EN NUESTRO ORDENADOR Y DAR LOS PRIMEROS PASOS</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>
                
                <capitulo paginas="22">
                    <titulo>CONCEPTOS BÁSICOS DE PROGRAMACIÓN ORIENTADA A OBJETOS. CLASES Y OBJETOS.</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>
                
                <capitulo paginas="12">
                    <titulo>ESCRITURA BÁSICA DE CÓDIGO Y ESTRUCTURAS DE DECISIÓN</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>
                
                <capitulo paginas="16">
                    <titulo>LIBRERÍAS DEL API DE JAVA. BIBLIOTECAS DE CLASES.</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>
                
                <capitulo paginas="22">
                    <titulo>CONSTRUIR UN PROGRAMA CON JAVA</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>

                <capitulo paginas="22">
                    <titulo>BUCLES, COLECCIONES DE OBJETOS Y RECORRIDOS DE COLECCIONES </titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>

                <capitulo paginas="22">
                    <titulo>BUCLES, COLECCIONES DE OBJETOS Y RECORRIDOS DE COLECCIONES</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>

                <capitulo paginas="22">
                    <titulo>MÁS CONCEPTOS Y CUESTIONES BÁSICAS DE JAVA</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>

                <capitulo paginas="22">
                    <titulo>HERENCIA EN JAVA. ¿QUÉ ES? ¿PARA QUÉ SIRVE?</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>

                <capitulo paginas="22">
                    <titulo>IR MÁS ALLÁ EN JAVA: SWING, GESTIÓN DE ERRORES Y MÁS.</titulo>
                    <contenido enlace="https://www.aprenderaprogramar.com/"/>
                </capitulo>
                
            </capitulos>
            <sinopsis>
